services:
  frontend:
    build:
      context: ./frontend
    image: yos-frontend:local
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: yos-backend:local
    environment:
      SERVER_PORT: "8080"
      FRONTEND_ORIGIN: "http://localhost"
      JWT_SECRET: "replace-in-prod"
      PUBLIC_ASSET_URL: "http://localhost:8080"
      AVATAR_DIR: "/tmp/yos-avatars"
    ports:
      - "8080:8080"
    volumes:
      - avatar_data:/tmp/yos-avatars
    depends_on:
      - minio
      - redis
      - timescaledb

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    pull_policy: never
    environment:
      POSTGRES_DB: yos
      POSTGRES_USER: yos
      POSTGRES_PASSWORD: yos123456
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    pull_policy: never
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    pull_policy: never
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  timescale_data:
  minio_data:
  avatar_data:
